services:
  db:
    image: postgres:14
    container_name: pokemon_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: pokemon_backend
    env_file:
      - .env
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
    ports:
      - "5002:5002"

  frontend:
    image: node:18
    container_name: frontend_app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install &&
            npm run dev -- --host"

volumes:
  postgres_data:
