services:
  db:
    image: postgres:14
    container_name: pokemon_db
    restart: always
    env_file: ./backend/.env  
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./backend/database_backup.sql:/docker-entrypoint-initdb.d/database_backup.sql  # Aquí montamos el script

  backend:
    container_name: pokemon_backend
    env_file: ./backend/.env
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"  # 🔥 Sin ":5432"
    ports:
      - "5002:5002"
volumes:
  postgres_data:
